### ISSUE TITLE
Add donation & cart logic to BOS app

### ISSUE THREAD

**Issue by lachlanglen** [PotLock/bos-app#60]

**Comment by flowscience** [comment]
Cart resets if new projects are added from a second tab without refreshing to sync.

Projects add to cart fine if the second tab is refreshed before adding a project. The UX issue is that it's easiest to scroll the home page and open multiple tabs for projects I want to donate to. However, I need to refresh each tab before adding to cart, otherwise the entire cart is erased and only that one (1) project just added remains in the cart.
